server:
  port: 8222
  eureka:
    client:
      registrer-with-eureka: false
      server:
        port: 8222
        spring:
          cloud:
            gateway:
              discovery:
                locator:
                  enabled: true
                routes:
                  - id: projets
                    uri: http://localhost:8090
                    predicates:
                      - Path=/api/v1/projets/**
                      - id: taches
                        uri: http://localhost:8070
                        predicates:
                          - Path=/api/v1/taches/**