<<<<<<< HEAD
eureka:
  client:
    register-with-eureka: false

spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      mvc:
       routes:
        - id: projets
          uri: http://localhost:8090
          predicates:
            - Path=/api/projets/**
        - id: taches
          uri: http://localhost:8070
          predicates:
            - Path=/api/taches/**
        - id: ressources
          uri: http://localhost:8081
          predicates:
                - Path=/api/ressources/**


server:
  port: 8222
=======
server:
  port: 8222
  eureka:
    client:
      registrer-with-eureka: false
      server:
        port: 8222
        spring:
          cloud:
            gateway:
              discovery:
                locator:
                  enabled: true
                routes:
                  - id: projets
                    uri: http://localhost:8090
                    predicates:
                      - Path=/api/v1/projets/**
                      - id: taches
                        uri: http://localhost:8070
                        predicates:
                          - Path=/api/v1/taches/**
>>>>>>> 4da7eadbc518f737fa888d5f7b277baff6fa49fb
