eureka:
  client:
    register-with-eureka: false

spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      mvc:
       routes:
        - id: projets
          uri: http://localhost:8090
          predicates:
            - Path=/api/projets/**
        - id: taches
          uri: http://localhost:8070
          predicates:
            - Path=/api/taches/**
        - id: ressources
          uri: http://localhost:8081
          predicates:
                - Path=/api/ressources/**


server:
  port: 8222