eureka:
  eureka:
    instance:
      hostname: localhost
    client:
      register-with-eureka: true
      service-url:
        defaultZone: http://localhost:8761/eureka

server:
  port: 8074
spring:
  application:
    name: utilsateur
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/authentication
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    flyway:
      locations: db/megration
      baseline-on-migrate: true


